collections:
  - name: azure.azcollection
    version: ">=2.0.0"
  - name: containers.podman
    version: ">=1.10.0"
  - name: community.general
    version: ">=6.0.0"
  - name: ansible.posix
    version: ">=1.4.0"