all:
  children:
    azure_vms:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
      vars:
        # Azure collection requirements
        ansible_python_interpreter: python3